api_platform:
    mapping:
        paths:
            [
                "%kernel.project_dir%/vendor/controleonline/integration/src/Entity",
                "%kernel.project_dir%/vendor/controleonline/integration/src/Resource",
            ]
    